#!/usr/bin/env bash
# Configures UFW to block all incoming traffic except ports 22, 443, and 80

sudo apt-get update -y
sudo apt-get install -y ufw
sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow required ports first
sudo ufw allow 22/tcp   # SSH
sudo ufw allow 443/tcp  # HTTPS
sudo ufw allow 80/tcp   # HTTP

# Enable firewall
sudo ufw --force enable

