#!/usr/bin/env bash
# This script installs Apache, creates a Hello Holberton page, and starts Apache

# Update package lists and install Apache
apt-get update -y

apt-get install -y apache2

# Create the page
echo "Hello Holberton" > /var/www/html/index.html

# Suppress ServerName warning
echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Start Apache in the foreground so the container keeps running
apache2ctl -D FOREGROUND
