#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header
# shellcheck disable=SC2154
apt-get update -y
apt-get install -y nginx
sed -i "s/server_name _;/server_name _;\\n\\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-available/default
service nginx restart
