#!/usr/bin/env bash
# Configure a new Ubuntu machine to redirect /redirect_me with 301

apt-get update -y
apt-get install nginx -y

# Add redirection block
sudo sed -i '/server_name _;/a location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
